#!/usr/bin/perl -w
# package App::P10N;
# use Moose;
# 
# with 'MooseX::Getopt';
# 
# has 'upload' => (is => 'rw', isa => 'Str');
# 
# my $app = __PACKAGE__->new_with_options();

use YAML qw(LoadFile);

my $gs_dir = 'generated-slides';
system(qw<rm -rf>, $gs_dir);
system('mkdir',    $gs_dir);

my $slides = LoadFile('slides');
my $slide_number = 0;
SLIDE:
for my $text (@$slides) {
    my $current_slide = sprintf("$gs_dir/slide%03d.svg", ++$slide_number);
    $text ||= '';
    if (ref $text) {
        if (my $slide = $text->{'slide'}) {
            my $file = $slide->{'file'} or die 'No file specified';
            if ($file !~ m/\.svg$/) {
                $file .= '.svg';
            }
            die "No such file $file"
                unless -f $file;
            if ($slide->{'gradual'} && 0) { # because I don't want that in the
                                            # uploaded presentation
                use XML::Easy::Text qw( xml10_read_document
                                        xml10_write_document );
                use XML::Easy::NodeBasics qw(xml_content_object xml_element);
                use File::Slurp;
                use Data::Dumper;

                $element = xml10_read_document(read_file($file));
                my $objects = $element->content();
                my @all_objects = @{$objects};
                my @o;
                for my $n (0 .. @all_objects-1) {
                    next if $n % 2 == 0;
                    push @o, $all_objects[$n];
                    next if $all_objects[$n]->type_name() eq 'defs';
                    my $element = xml_element('svg',
                        { width => "297mm", height => "210mm",
                          'xmlns'       => 'http://www.w3.org/2000/svg',
                          'xmlns:xlink' => 'http://www.w3.org/1999/xlink' },
                        @o);
                    open my $SLIDE, '>', sprintf("$gs_dir/slide%03d.svg",
                                                 $slide_number++)
                        or die $!;
                    print {$SLIDE} xml10_write_document($element, "UTF-8");
                }
                --$slide_number;
            }
            else {
                system('cp', $file, $current_slide);
            }
            next SLIDE;
        }
        die 'Unknown thing ', $text;
    }

    open(my $SLIDE, '>', $current_slide);
    print {$SLIDE} <<"SVG";
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   version="1.0"
   width="297mm"
   height="210mm">
  <image
     xlink:href="../3583523428-dancingshiva.jpg"
     x="-6.3408203"
     y="-27.864227"
     width="1065.0438"
     height="799.82294" />
  <text
     x="526.11737"
     y="388.51123"
     xml:space="preserve"
     style="font-size:48px;text-align:center;text-anchor:middle;fill:#000000;fill-opacity:1;stroke:none;font-family:Optima">$text</text>
</svg>
SVG
}

my $inkscape_executable
    = '/Applications/Inkscape.app/Contents/Resources/bin/inkscape';

system
    "$inkscape_executable --export-text-to-path --export-bbox-page "
    . "--without-gui --file=$gs_dir/slide$_.svg "
    . "--export-pdf=$gs_dir/slide$_.pdf 2> /dev/null"
        for map { sprintf '%03d', $_ } 1..$slide_number;

system
    'gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite'
    . " -sOutputFile=talk.pdf $gs_dir/*.pdf";

